{'status': u'New', 'web_link': u'https://bugs.launchpad.net/cinder/+bug/1123146', 'title': u"xenapi:XenAPINFS does not handle plugin's RetryableError"}